name: selvis_flutter
description: Приложение для сайта selvis.com
version: 1.0.15+20

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_advanced_networkimage: any
  path_provider: any
  http: any
  intl: any
  barcode_scan: any
  sentry: any
  dotenv: any
  shared_preferences: any
  flutter_device_type: any
  device_info: any
  package_info: any
  flutter_typeahead: any
  flutter_sticky_header: any
  uni_links:
    git:
      url: git://github.com/avioli/uni_links
      ref: ac96aeb8dc5b90e56da817af17ef7034abdd0c7f
  multi_navigator_bottom_bar:
    git:
      url: git://github.com/DCrow/flutter_multi_navigator_bottom_bar
      ref: 4f095d413d54a2dece20c3342a1eaa621111e901

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  assets:
    - .app_env
  uses-material-design: true
